language: cpp
os: linux
sudo: required
dist: trusty
compiler: gcc
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y qt4-qmake libboost-dev libboost-program-options-dev
script: ./debug.sh; ./release.sh
notifications:
    email:
        recipients: aijunbai@gmail.com
        on_success: change
        on_failure: always

